### ISSUE TITLE
Please can you use semver?

### ISSUE THREAD

**Issue by punkeel** [jrf0110/8track#28]
The changes introduced by #23 and related PRs are not backward compatible and should have resulted in a major version bump; which would have prevented npm/yarn from upgrading the dependency on 8track and breaking our application.

Could you please consider using [semver](semver.org) so that breaking changes are properly identified in the future?

**Comment by jrf0110** [comment]
Hey, @punkeel - apologies for the mishap. I generally do try and follow semver. Robert's changes seemed to me at the time to only be _adding APIs_, so I had assumed it was not breaking (other than the Context constructor, which doesn't have its signature documented anyway).

Anywho, it's nice to know 8track is being used by other folks! Apologies again for the breaking change. We'll definitely be more vigilant next time around.

**Comment by punkeel** [comment]
Thanks! :)
